---
title: Zefiros Events
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@zefirosevents.gr
description: 'Cafe Bar Restaurant Events Νέα Αρτάκη, Χαλκίδα, Εύβοια

'
baseurl: ''
url: http://zefirosevents.gr
twitter_username: zefiroscafe
markdown: kramdown
permalink: "/:categories/:title.html"
gems:
- jekyll-sitemap
