# Site settings
title: Zefiros Events
email: info@zefirosevents.gr
description: > # this means to ignore newlines until "baseurl:"
  Cafe Bar Restaurant Events
  Νέα Αρτάκη, Χαλκίδα, Εύβοια
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zefirosevents.gr" # the base hostname & protocol for your site
twitter_username: zefiroscafe

# Build settings
markdown: kramdown

permalink: /:categories/:title.html

# gems
gems:
  - jekyll-sitemap
